packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Auth
  "@auth/core": 0.37.2
  "@auth/drizzle-adapter": ~1.7.4
  "next-auth": 5.0.0-beta.25

  # Dev tooling
  eslint: 9.16.0
  prettier: 3.3.3
  tailwindcss: 3.4.15
  typescript: 5.7.2

  # Misc
  "@radix-ui/react-icons": "1.3.2"
  "@types/node": 22.10.2
  dotenv-cli: 7.4.4
  superjson: 2.2.1
  vitest: 2.1.8
  zod: 3.23.8
  date-fns: 4.1.0

  # Next
  next: 15.1.2
  "@t3-oss/env-nextjs": 0.10.1

  # React
  react: 19.0.0
  react-dom: 19.0.0
  "@types/react": 19.0.1
  "@types/react-dom": 19.0.2

  # Tanstack & tRPC
  "@tanstack/react-query": 5.62.7
  "@trpc/client": 11.0.0-rc.660
  "@trpc/react-query": 11.0.0-rc.660
  "@trpc/server": 11.0.0-rc.660
