# .npmrc settings
nodeLinker: hoisted
linkWorkspacePackages: true
savePrefix: ""

packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Auth
  "@auth/core": 0.37.2
  "@auth/drizzle-adapter": ~1.7.4
  next-auth: 5.0.0-beta.25

  # Dev tooling
  dotenv-cli: 8.0.0
  eslint: 9.24.0
  prettier: 3.5.3
  tailwindcss: 3.4.15
  typescript: 5.8.3

  # Misc
  "@radix-ui/react-icons": 1.3.2
  "@types/node": 22.14.0
  date-fns: 4.1.0

  # Next
  next: 15.2.4
  "@t3-oss/env-nextjs": 0.12.0

  # React
  react: 19.1.0
  react-dom: 19.1.0
  "@types/react": 19.1.0
  "@types/react-dom": 19.1.1

  # Schema & validation
  devalue: 5.1.1
  drizzle-kit: 0.30.1
  drizzle-orm: 0.38.2
  drizzle-zod: 0.7.0
  zod: 3.24.2

  # Tanstack & tRPC
  "@tanstack/react-query": 5.69.0
  "@trpc/client": 11.0.0
  "@trpc/react-query": 11.0.0
  "@trpc/server": 11.0.0

  # Testing
  vitest: 3.1.1
