packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Auth
  "@auth/core": 0.37.2
  "@auth/drizzle-adapter": ~1.7.4
  "next-auth": 5.0.0-beta.25

  # Dev tooling
  eslint: 9.16.0
  prettier: 3.3.3
  tailwindcss: 3.4.15
  typescript: 5.7.2

  # Misc
  superjson: 2.2.1
  zod: 3.23.8
  "@types/node": 22.10.2

  # Next
  next: 15.1.0
  "@t3-oss/env-nextjs": 0.10.1

  # React
  react: 19.0.0
  react-dom: 19.0.0
  "@types/react": 19.0.1
  "@types/react-dom": 19.0.2

  # Tanstack & tRPC
  "@tanstack/react-query": 5.61.0
  "@trpc/client": 11.0.0-rc.638
  "@trpc/react-query": 11.0.0-rc.638
  "@trpc/server": 11.0.0-rc.638
